version: '3.8'

services:
  server_a:
    build: ./server_a
    ports:
      - "5000:5000"
    depends_on:
      - db

  server_b:
    build: ./server_b
    ports:
      - "5001:5000"
    depends_on:
      - server_a

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: flaskdb
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
